logging:
  level:
    root: INFO
    org.flywaydb: DEBUG

spring:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
